// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwdXrC-Mz_zqQwnFydSw8ux6roHZZkPEw',
    appId: '1:15060351547:web:71b25621310e2161d57a1e',
    messagingSenderId: '15060351547',
    projectId: 'study-app-29adb',
    authDomain: 'study-app-29adb.firebaseapp.com',
    storageBucket: 'study-app-29adb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGgpDhon8umEQmal-0GzonCyutWIvbY4',
    appId: '1:15060351547:android:0134e870125145ccd57a1e',
    messagingSenderId: '15060351547',
    projectId: 'study-app-29adb',
    storageBucket: 'study-app-29adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1QW27eCXbQxmxURhGKp4gYA0t3JjgIM',
    appId: '1:15060351547:ios:a9177709aa47a965d57a1e',
    messagingSenderId: '15060351547',
    projectId: 'study-app-29adb',
    storageBucket: 'study-app-29adb.appspot.com',
    iosClientId: '15060351547-pbe10c5em8ng9d8fanme8sq87uvmmj03.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1QW27eCXbQxmxURhGKp4gYA0t3JjgIM',
    appId: '1:15060351547:ios:a9177709aa47a965d57a1e',
    messagingSenderId: '15060351547',
    projectId: 'study-app-29adb',
    storageBucket: 'study-app-29adb.appspot.com',
    iosClientId: '15060351547-pbe10c5em8ng9d8fanme8sq87uvmmj03.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
